/* Replace the illustrative assets with the client's approved originals here.
 * placeholder: false removes the illustration label. Do not change it until
 * image, brand, service and project details have been verified together.
 */
globalThis.KEYSAFE_DATA = {
  contact: { email: 'commercial@keysafe.tn', phone: '+21627764657', displayPhone: '+216 27 764 657' },
  brands: { tesca: 'TESCA', psc: 'PSC', socohuile: 'SOCOHUILE' },
  services: [
    { id: 'bureaux', number: '01', icon: 'door', short: 'Bureaux', title: 'Identification des bureaux', heading: 'Des espaces qui se lisent.', description: 'Un repérage clair des bureaux, services et espaces communs, dans le respect de votre identité.', detail: 'Plaques de porte, noms des services et repères directionnels : une même logique visuelle pour accueillir et orienter.', tags: ['Plaques de porte', 'Repères directionnels', 'Identité visuelle'], image: 'assets/bureaux.webp' },
    { id: 'locaux', number: '02', icon: 'settings', short: 'Locaux techniques', title: 'Identification des locaux techniques', heading: 'Identifier avant d’intervenir.', description: 'Des locaux identifiés sans ambiguïté pour faciliter le repérage et les interventions.', detail: 'Nommer les espaces techniques et rendre les restrictions d’accès visibles, au plus près des équipements.', tags: ['Désignation des locaux', 'Repérage des accès', 'Supports adaptés'], image: 'assets/locaux.webp' },
    { id: 'risques', number: '03', icon: 'warning', short: 'Risques spécifiques', title: 'Affiches de risques spécifiques par local', heading: 'Le risque compris, au premier regard.', description: 'Des messages ciblés pour rendre visibles les dangers et les consignes propres à chaque local.', detail: 'Associer les dangers identifiés aux messages de prévention et aux équipements de protection adaptés à l’activité.', tags: ['Dangers identifiés', 'Consignes ciblées', 'Équipements de protection'], image: 'assets/risques.svg' },
    { id: 'circulation', number: '04', icon: 'route', short: 'Circulation', title: 'Plans de circulation', heading: 'Des flux lisibles. Des trajets sereins.', description: 'Une lecture claire des déplacements, des accès et des zones de circulation sur votre site.', detail: 'Visualiser les cheminements piétons, les parcours des véhicules et les points de croisement pour mieux organiser les flux.', tags: ['Cheminements piétons', 'Flux des véhicules', 'Accès et orientation'], image: 'assets/circulation.svg' },
    { id: 'evacuation', number: '05', icon: 'exit', short: 'Évacuation', title: 'Plans d’évacuation', heading: 'Savoir où aller. Sans hésiter.', description: 'Des repères accessibles pour comprendre les parcours, les sorties et les points de rassemblement.', detail: 'Une représentation du site pensée pour situer les personnes et rendre les itinéraires et moyens de secours identifiables.', tags: ['Vous êtes ici', 'Issues et itinéraires', 'Points de rassemblement'], image: 'assets/evacuation-plan.svg' }
  ],
  projects: [
    { id: 'tesca-bureaux', brand: 'tesca', service: 'bureaux', title: 'Une identité, à chaque porte.', subtitle: 'Identification & orientation', image: 'assets/bureaux.webp', gallery: ['assets/bureaux.webp', 'assets/bureaux-detail.svg'], placeholder: true },
    { id: 'psc-locaux', brand: 'psc', service: 'locaux', title: 'Les bons repères techniques.', subtitle: 'Locaux techniques & accès', image: 'assets/locaux.webp', gallery: ['assets/locaux.webp', 'assets/risques.svg'], placeholder: true },
    { id: 'socohuile-risques', brand: 'socohuile', service: 'risques', title: 'La prévention s’affiche.', subtitle: 'Risques spécifiques par local', image: 'assets/risques.svg', gallery: ['assets/risques.svg', 'assets/locaux.webp'], placeholder: true },
    { id: 'tesca-circulation', brand: 'tesca', service: 'circulation', title: 'Chaque flux trouve sa voie.', subtitle: 'Plan de circulation', image: 'assets/circulation.svg', gallery: ['assets/circulation.svg', 'assets/industry-hero.webp'], placeholder: true },
    { id: 'psc-evacuation', brand: 'psc', service: 'evacuation', title: 'Le chemin vers la sécurité.', subtitle: 'Plan d’évacuation', image: 'assets/evacuation-plan.svg', gallery: ['assets/evacuation-plan.svg', 'assets/circulation.svg'], placeholder: true },
    { id: 'socohuile-locaux', brand: 'socohuile', service: 'locaux', title: 'Des accès clairement identifiés.', subtitle: 'Identification des locaux', image: 'assets/locaux.webp', gallery: ['assets/locaux.webp', 'assets/risques.svg'], placeholder: true },
    { id: 'psc-bureaux', brand: 'psc', service: 'bureaux', title: 'S’orienter devient naturel.', subtitle: 'Signalétique des bureaux', image: 'assets/bureaux.webp', gallery: ['assets/bureaux.webp', 'assets/bureaux-detail.svg'], placeholder: true },
    { id: 'socohuile-circulation', brand: 'socohuile', service: 'circulation', title: 'Un site, des parcours lisibles.', subtitle: 'Organisation des flux', image: 'assets/industry-hero.webp', gallery: ['assets/industry-hero.webp', 'assets/circulation.svg'], placeholder: true },
    { id: 'tesca-evacuation', brand: 'tesca', service: 'evacuation', title: 'Des repères pour agir.', subtitle: 'Évacuation & rassemblement', image: 'assets/evacuation-plan.svg', gallery: ['assets/evacuation-plan.svg', 'assets/circulation.svg'], placeholder: true },
    { id: 'tesca-locaux', brand: 'tesca', service: 'locaux', title: 'Reconnaître chaque espace.', subtitle: 'Identification des locaux techniques', image: 'assets/locaux.webp', gallery: ['assets/locaux.webp', 'assets/risques.svg'], placeholder: true },
    { id: 'tesca-risques', brand: 'tesca', service: 'risques', title: 'Des messages qui comptent.', subtitle: 'Affiches de risques par local', image: 'assets/risques.svg', gallery: ['assets/risques.svg', 'assets/locaux.webp'], placeholder: true },
    { id: 'psc-risques', brand: 'psc', service: 'risques', title: 'Anticiper dès le premier regard.', subtitle: 'Risques & prévention', image: 'assets/risques.svg', gallery: ['assets/risques.svg', 'assets/locaux.webp'], placeholder: true },
    { id: 'psc-circulation', brand: 'psc', service: 'circulation', title: 'Des parcours bien pensés.', subtitle: 'Flux & cheminements', image: 'assets/circulation.svg', gallery: ['assets/circulation.svg', 'assets/industry-hero.webp'], placeholder: true },
    { id: 'socohuile-bureaux', brand: 'socohuile', service: 'bureaux', title: 'L’accueil commence par un repère.', subtitle: 'Bureaux & espaces communs', image: 'assets/bureaux.webp', gallery: ['assets/bureaux.webp', 'assets/bureaux-detail.svg'], placeholder: true },
    { id: 'socohuile-evacuation', brand: 'socohuile', service: 'evacuation', title: 'Une lecture claire des issues.', subtitle: 'Plans d’évacuation', image: 'assets/evacuation-plan.svg', gallery: ['assets/evacuation-plan.svg', 'assets/circulation.svg'], placeholder: true }
  ],
  videos: [
    { id: 'incendie', title: 'Face au feu, chaque seconde compte.', category: 'Formation incendie', client: 'Intervention KeySafe', description: 'Prévenir, réagir, maîtriser et coordonner : la formation à l’épreuve du terrain.', src: 'assets/incendie.mp4', poster: 'assets/incendie-poster.jpg', source: 'https://www.linkedin.com/feed/update/urn:li:activity:7493019414590676992/' },
    { id: 'evacuation', title: 'Se préparer, ensemble.', category: 'Exercice d’évacuation', client: 'EL KHOMSA · ROSE BLANCHE Group', description: 'Simulation d’évacuation d’urgence conçue et animée par KeySafe.', src: 'assets/evacuation.mp4', poster: 'assets/evacuation-poster.jpg', source: 'https://www.linkedin.com/feed/update/urn:li:activity:7484900739761213440/' },
    { id: 'safety-day', title: 'Faire vivre la prévention.', category: 'Safety Day', client: 'BONDIN', description: 'Les temps forts d’une journée consacrée à la prévention et à l’engagement des équipes.', src: 'assets/safety-day.mp4', poster: 'assets/safety-day-poster.jpg', source: 'https://www.linkedin.com/feed/update/urn:li:activity:7479833958659215360/' },
    { id: 'exercice', title: 'Cultiver les bons réflexes.', category: 'Culture sécurité', client: 'Ciments Jbel Oust', description: 'Un exercice pour pratiquer les protocoles et renforcer les réflexes collectifs.', src: 'assets/exercice.mp4', poster: 'assets/exercice-poster.jpg', source: 'https://www.linkedin.com/feed/update/urn:li:activity:7477275452492095488/' }
  ]
};

globalThis.KEYSAFE_FILTER = (projects, brand = 'all', service = 'all') => projects.filter(project =>
  (brand === 'all' || project.brand === brand) && (service === 'all' || project.service === service)
);
